name: test

on:
  push:
    branches: [core]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: "."
          doxyfile-path: "Doxyfile"
      - name: Upload Output Directory
        uses: actions/upload-artifact@v3
        with:
          name: doc-files
          path: html
          retention-days: 1
  copy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: download
        uses: actions/download-artifact@v2
        with:
          name: doc-files
          path: docs
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: putian9935
          author_email: pl35@u.nus.edu
          message: "Update docs"
          branch: gh-pages
          add: '["docs/*"]'
